export default {
  1: [
    {
      id: 1,
      login: 'Account Manager',
      email: 'account@sunrise.com',
      picture: '/img/mocks/tester-avatar.webp',
      role: 'Account manager',
      roleCode: 'manager',
    },
    {
      id: 2,
      login: 'Karen Marie Ørsted Andersen',
      email: 'karen.andersen@sunrise.com',
      picture: '/img/mocks/account-photo-1.webp',
      role: 'Account manager',
      roleCode: 'manager',
    },
    {
      id: 3,
      login: 'Wendy Russell',
      email: 'wendy.russell@sunrise.com',
      picture: '/img/mocks/account-photo-2.webp',
      role: 'Admin',
      roleCode: 'admin',
    },
    {
      id: 4,
      login: 'Gladys Cooper',
      email: 'gladys.cooper@sunrise.com',
      picture: '/img/mocks/account-photo-3.webp',
      role: 'Admin',
      roleCode: 'admin',
    },
    {
      id: 5,
      login: 'Gloria Fischer',
      email: 'gloria.fischer@sunrise.com',
      picture: '/img/mocks/account-photo-4.webp',
      role: 'Agent',
      roleCode: 'agent',
    },
    {
      id: 6,
      login: 'Arthur Pena',
      email: 'arthur.pena@sunrise.com',
      picture: '/img/mocks/account-photo-5.webp',
      role: 'Agent',
      roleCode: 'agent',
    },
    {
      id: 7,
      login: 'Clémentine Louis',
      email: 'clementine.louis@sunrise.com',
      picture: '/img/mocks/account-photo-6.webp',
      role: 'Agent',
      roleCode: 'agent',
    },
    {
      id: 8,
      login: 'Francisco Lane',
      email: 'francisco.lane@sunrise.com',
      picture: '/img/mocks/account-photo-7.webp',
      role: 'Agent',
      roleCode: 'agent',
    },
    {
      id: 9,
      login: 'Darrell Richards',
      email: 'darrell.richards@sunrise.com',
      picture: '/img/mocks/account-photo-8.webp',
      role: 'Agent',
      roleCode: 'agent',
    },
    {
      id: 10,
      login: 'Max Hawkins',
      email: 'max.hawkins@sunrise.com',
      picture: '/img/mocks/account-photo-9.webp',
      role: 'External reviewer',
      roleCode: 'reviewer',
    },
  ],
  2: [
    {
      id: 11,
      login: 'test',
      email: 'test@sunrise.com',
      picture: null,
      role: 'Account manager',
      roleCode: 'manager',
    },
    {
      id: 12,
      login: 'Test',
      email: 'test@sunrise.com',
      picture: '/img/mocks/tester-avatar.webp',
      role: 'Account manager',
      roleCode: 'manager',
    },
    {
      id: 13,
      login: 'Test',
      email: 'test222@sunrise.com',
      picture: null,
      role: 'Admin',
      roleCode: 'admin',
    },
    {
      id: 14,
      login: 'Test',
      email: 'test@sunrise.com',
      picture: null,
      role: 'Agent',
      roleCode: 'agent',
    },
    {
      id: 15,
      login: 'Test',
      email: 'trest@sunrise.com',
      picture: null,
      role: 'External reviewer',
      roleCode: 'reviewer',
    },
  ],
};
